### ISSUE TITLE
Can not log in with after registering a new account

### ISSUE THREAD

**Issue by oakland-poduska** [jnick1/MyCollege#58]
User exists in database but exception appears.

InvalidArgumentException: Student->__construct2(rmgiveaway8@gmail.com, 2) - Student not found in C:\wamp64\www\MyCollege\classes\entities\Student.php:129
Stack trace:
#0 C:\wamp64\www\MyCollege\classes\entities\DataBasedEntity.php(48): Student->__construct2('rmgiveaway8@gma...', 2)
#1 C:\wamp64\www\MyCollege\classes\Authenticator.php(46): DataBasedEntity->__construct('rmgiveaway8@gma...', 2)
#2 C:\wamp64\www\MyCollege\classes\Controller.php(568): Authenticator::login('rmgiveaway8@gma...', 'bigpassword')
#3 C:\wamp64\www\MyCollege\classes\Controller.php(385): Controller->processPOST()
#4 C:\wamp64\www\MyCollege\pages\login\login.php(7): Controller->processREQUEST()
#5 {main}

**Comment by kalevias** [comment]
Referenced by https://github.com/jnick1/MyCollege/commit/e606fc098c219d1bf15e5b489269f090264c240e by @oakland-poduska
